### ISSUE TITLE
Add tests that forces and virials are consistent with energy

### ISSUE THREAD

**Issue by cortner** [JuliaMolSim/AtomsCalculators.jl#14]
Probably a finite difference test. The test in ACEbase has served me well over the years: 

https://github.com/ACEsuit/ACEbase.jl/blob/main/src/testing.jl

It is great for debugging and can also be automated. For something like DFT where forces are inherentily noisy it might be less well suited.

**Comment by mfherbst** [comment]
Typically DFT forces are consistent if you choose numerical tolerances low enough (we do these tests) so should not be too much of a problem (provided one can tweak the tolerances in a generic way).

**Comment by cortner** [comment]
addressed in AtomsCalculatorsUtiltiies
