### ISSUE TITLE
@generate_interface bug : Requires AtomsCalculators.functionname

### ISSUE THREAD

**Issue by cortner** [JuliaMolSim/AtomsCalculators.jl#19]
```
@generate_interface function AtomsCalculators.potential_energy(...)
```
is accepted while 
```
@generate_interface function potential_energy(...)
```
fails even if `potential_energy` is imported.

**Comment by tjjarvinen** [comment]
This is actually intended behavior.

If there are name conflicts with other packages, you need to solve them with prefixing module name. This behavior forces you to add the module name to the call and thus always get it linked to the correct package.

**Comment by cortner** [comment]
if potential_energy is imported successfully then there can be no conflict I think.

**Comment by tjjarvinen** [comment]
No that does not rule out the possibility of this error.

You can do `using AtomsCalculators : potential_energy` and after that import some other package with `potential_energy` and the macro would not know which one to use after that.

I do not say that it could not be implemented safely. But I need to think can this be implemented.

**Comment by cortner** [comment]
But that would be user error.

**Comment by tjjarvinen** [comment]
That is correct. But this was done to not allow users to make that error.

**Comment by cortner** [comment]
it's fine. I do not like it but I will live with it.
