### ISSUE TITLE
@generate_interface bug : cannot use args...

### ISSUE THREAD

**Issue by cortner** [JuliaMolSim/AtomsCalculators.jl#20]
To implement both simple and parameterized assembly at the same time I tried to do 
```
@generate_interface function AtomsCalculators.potential_energy(sys, calc::SitePotential, args...; kwards...)  ... 
```
this fails with 
```
LoadError: Could not determine calculators type
in expression starting at ...
```

**Comment by tjjarvinen** [comment]
Here missing a `function` does this mean you tried to have `f(x) = g(x)` style statement?

The reason for this not working is that it would complicate the macro implementation and was left out from the implementation. It could be implemented, but it is not easy...

**Comment by cortner** [comment]
I did use the `function` style. It has nothing to with that.

**Comment by tjjarvinen** [comment]
Ah sorry I missread completely.

The macro checks that you do not have additional `args...`. This is a basic feature to inform you that your implenetation is not accordingly the interface.

When the lux model update lands you cannot use the macro implement this at all.

If you still want to have this in. Then you need to implement all by hand. But I advise against it.

**Comment by cortner** [comment]
No, I prefer we wait for the lux interface. It just means we will also wait porting the parameterized potentials until that is finally merged.

**Comment by cortner** [comment]
I'm happy to close this then.

**Comment by tjjarvinen** [comment]
If you want to use additional `args...` then implement a call without them and then additional one (without macro) that has `args...` that is the safest way.

**Comment by cortner** [comment]
I would prefer to not maintain 10 copies of the same code.
