### ISSUE TITLE
Weird default tolerance in testing function

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/AtomsCalculators.jl#29]
This default `rtol` of `1e8` strikes me as odd. 

https://github.com/JuliaMolSim/AtomsCalculators.jl/blob/2ab874239ae5b08843c7dd5e938d6ccb8f5c8e0d/src/submodules/Testing.jl#L31

I have not read through the full mechanics, but I'd expect something `<1`, so I suspect it's a typo and `1e-8` is meant.

**Comment by cortner** [comment]
good catch. And it should probably be sqrt(precision)

**Comment by tjjarvinen** [comment]
Thanks for notising this.

The reason for the correct value 1e-8 is that only very special methods have accuracy more than 8 significant numbers. So there should be no need smaller tolerance in practive.

On the other hand there can be issues with multithreading and even different implementations of calculators for different calls (forces vs energy_forces etc.) that cause small variations. So, it is better to have relatively loose tolerance here.
